---
title: "Tekjur á almennum og opinberum vinnumarkaði"
author: "Brynjólfur Gauti Guðrúnar Jónsson"
date: "2022/04/08"
format: 
    html:
        code-fold: true
        toc: true
        toc-location: right
        
editor: source
fig-width: 10
---

```{r}
#| include = FALSE
knitr::opts_chunk$set(warning = FALSE, message = FALSE, echo = TRUE,
                      fig.asp = 0.621, fig.width = 10, out.width = "100%")
library(pxweb)
library(tidyverse)
library(scales)
library(cowplot)
library(ggthemes)
library(ggtext)
library(gganimate)
```

# Lesa inn gögn



```{r}
url <- "https://px.hagstofa.is:443/pxis/api/v1/is/Samfelag/launogtekjur/1_laun/1_laun/VIN02004.px"

px_vars <- pxweb_get(url)

query_list <- list(
    "Ár" = c("*"),
    "Launþegahópur" = c("*"),
    "Starfsstétt" = c("*"),
    "Kyn" = c("*"),
    "Laun og vinnutími" = c("2"),
    "Eining" = c("*")
)


d <- pxweb_get(url, query = pxweb_query(query_list), verbose = FALSE) |> 
    as.data.frame() |> 
    as_tibble() |> 
    janitor::clean_names() |> 
    mutate(ar = parse_number(ar)) |> 
    rename(laun = dreifing_launa_fullvinnandi_launafolks_eftir_launthegahopi_starfsstett_og_kyni) |> 
    filter(str_detect(eining, "\\%")) |> 
    mutate(eining = parse_number(eining)/100) |> 
    select(-laun_og_vinnutimi) |> 
    filter(launthegahopur %in% c("Starfsmenn á almennum vinnumarkaði",
                                 "Opinberir starfsmenn - alls"))

```

# Myndir

## 2014 - 2021

### Krónutölubreyting

```{r, fig.width = 10, fig.asp = 0.6, out.width = "100%"}
plot_dat <- d |> 
    filter(kyn == "Alls",
           ar %in% c(2014, 2021),
           !starfsstett %in% c("Alls", "Iðnaðarmenn", "Verkafólk")) |> 
    mutate(launthegahopur = fct_recode(launthegahopur,
                                       "Almennur markaður" = "Starfsmenn á almennum vinnumarkaði",
                                       "Hið opinbera" = "Opinberir starfsmenn - alls") |> 
               as.character() |> 
               as_factor(),
           laun = laun * 1000,
           ar = ifelse(ar == max(ar), "eftir", "fyrir")) |> 
    pivot_wider(names_from = ar, values_from = laun) |> 
    mutate(munur = eftir - fyrir,
           nr = starfsstett |> str_replace_all("[a-zA-Z áíéóðþö \\-]", "") |> parse_number(),
           starfsstett = str_replace(starfsstett, "\\([0-9]\\)", ""),
           starfsstett = fct_reorder(starfsstett, nr))

p <- plot_dat |> 
    ggplot(aes(eining, munur)) +
    geom_line(aes(lty = launthegahopur)) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(0, 1.08),
                       labels = label_percent(),
                       breaks = seq(0.1, 0.9, by = 0.1),
                       expand = expansion()) +
    scale_y_continuous(labels = label_number()) +
    guides(lty = guide_legend(label.position = "top", keywidth = unit(0.1, "npc"))) +
    facet_wrap("starfsstett", scales = "free_y") +
    theme_tufte() +
    theme(legend.position = "top",
          legend.box.margin = margin(),
          legend.margin = margin(l = 2, r = 2),
          axis.title.y = element_text(hjust = 0),
          axis.title.x = element_text(hjust = 0)) +
    labs(x = "Tekjutíund",
         y = "Launahækkun (Krónur)",
         lty = NULL,
         title = "Dreifing launahækkana (í krónutölu) frá 2014 - 2021",
         subtitle = NULL,
         caption = "Kóði: https://github.com/bgautijonsson/tekjur")

p

ggsave(plot = p, filename = "kr_breyting_2014-2021.png",
       width = 8, height = 0.7 * 8, scale = 1.3, bg = "white")
```

### Prósentubreyting

```{r, fig.width = 10, fig.asp = 0.6, out.width = "100%"}
plot_dat <- d |> 
    filter(kyn == "Alls",
           ar %in% c(2014, 2021),
           !starfsstett %in% c("Alls", "Iðnaðarmenn", "Verkafólk")) |> 
    mutate(launthegahopur = fct_recode(launthegahopur,
                                       "Almennur markaður" = "Starfsmenn á almennum vinnumarkaði",
                                       "Hið opinbera" = "Opinberir starfsmenn - alls") |> 
               as.character() |> 
               as_factor(),
           laun = laun * 1000,
           ar = ifelse(ar == max(ar), "eftir", "fyrir")) |> 
    pivot_wider(names_from = ar, values_from = laun) |> 
    mutate(munur = eftir/fyrir,
           nr = starfsstett |> str_replace_all("[a-zA-Z áíéóðþö \\-]", "") |> parse_number(),
           starfsstett = str_replace(starfsstett, "\\([0-9]\\)", ""),
           starfsstett = fct_reorder(starfsstett, nr))

p <- plot_dat |> 
    ggplot(aes(eining, munur)) +
    geom_line(aes(lty = launthegahopur)) +
    # geom_text(data = plot_dat |> filter(eining == max(eining)),
    #           aes(label = launthegahopur),
    #           hjust = 0, nudge_x = 0.01) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(0, 1.08),
                       labels = label_percent(),
                       breaks = seq(0.1, 0.9, by = 0.1),
                       expand = expansion()) +
    scale_y_continuous(labels = function(x) percent(x - 1)) +
    guides(lty = guide_legend(label.position = "top", keywidth = unit(0.1, "npc"))) +
    facet_wrap("starfsstett", scales = "free_y") +
    theme_tufte() +
    theme(legend.position = "top",
          legend.box.margin = margin(),
          legend.margin = margin(l = 2, r = 2),
          axis.title.y = element_text(hjust = 0),
          axis.title.x = element_text(hjust = 0)) +
    labs(x = "Tekjutíund",
         y = "Launahækkun (%)",
         lty = NULL,
         title = "Dreifing launahækkana (í prósentum) frá 2014 - 2021",
         subtitle = NULL,
         caption = "Kóði: https://github.com/bgautijonsson/tekjur")

p

p

ggsave(plot = p, filename = "hlutf_breyting_2014-2021.png",
       width = 8, height = 0.7 * 8, scale = 1.3, bg = "white")
```


## 2019 - 2021

### Krónutölubreyting

```{r, fig.width = 10, fig.asp = 0.6, out.width = "100%"}
plot_dat <- d |> 
    filter(kyn == "Alls",
           ar %in% c(2019, 2021),
           !starfsstett %in% c("Alls", "Iðnaðarmenn", "Verkafólk")) |> 
    mutate(launthegahopur = fct_recode(launthegahopur,
                                       "Almennur markaður" = "Starfsmenn á almennum vinnumarkaði",
                                       "Hið opinbera" = "Opinberir starfsmenn - alls") |> 
               as.character() |> 
               as_factor(),
           laun = laun * 1000,
           ar = ifelse(ar == max(ar), "eftir", "fyrir")) |> 
    pivot_wider(names_from = ar, values_from = laun) |> 
    mutate(munur = eftir - fyrir,
           nr = starfsstett |> str_replace_all("[a-zA-Z áíéóðþö \\-]", "") |> parse_number(),
           starfsstett = str_replace(starfsstett, "\\([0-9]\\)", ""),
           starfsstett = fct_reorder(starfsstett, nr))

p <- plot_dat |> 
    ggplot(aes(eining, munur)) +
    geom_line(aes(lty = launthegahopur)) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(0, 1.08),
                       labels = label_percent(),
                       breaks = seq(0.1, 0.9, by = 0.1),
                       expand = expansion()) +
    scale_y_continuous(labels = label_number()) +
    guides(lty = guide_legend(label.position = "top", keywidth = unit(0.1, "npc"))) +
    facet_wrap("starfsstett", scales = "free_y") +
    theme_tufte() +
    theme(legend.position = "top",
          legend.box.margin = margin(),
          legend.margin = margin(l = 2, r = 2),
          axis.title.y = element_text(hjust = 0),
          axis.title.x = element_text(hjust = 0)) +
    labs(x = "Tekjutíund",
         y = "Launahækkun (Krónur)",
         lty = NULL,
         title = "Dreifing launahækkana (í krónutölu) frá 2019 - 2021",
         subtitle = NULL,
         caption = "Kóði: https://github.com/bgautijonsson/tekjur")

p

ggsave(plot = p, filename = "kr_breyting_2019-2021.png",
       width = 8, height = 0.7 * 8, scale = 1.3, bg = "white")
```

### Prósentubreyting

```{r, fig.width = 10, fig.asp = 0.6, out.width = "100%"}
plot_dat <- d |> 
    filter(kyn == "Alls",
           ar %in% c(2019, 2021),
           !starfsstett %in% c("Alls", "Iðnaðarmenn", "Verkafólk")) |> 
    mutate(launthegahopur = fct_recode(launthegahopur,
                                       "Almennur markaður" = "Starfsmenn á almennum vinnumarkaði",
                                       "Hið opinbera" = "Opinberir starfsmenn - alls") |> 
               as.character() |> 
               as_factor(),
           laun = laun * 1000,
           ar = ifelse(ar == max(ar), "eftir", "fyrir")) |> 
    pivot_wider(names_from = ar, values_from = laun) |> 
    mutate(munur = eftir/fyrir,
           nr = starfsstett |> str_replace_all("[a-zA-Z áíéóðþö \\-]", "") |> parse_number(),
           starfsstett = str_replace(starfsstett, "\\([0-9]\\)", ""),
           starfsstett = fct_reorder(starfsstett, nr))

p <- plot_dat |> 
    ggplot(aes(eining, munur)) +
    geom_line(aes(lty = launthegahopur)) +
    # geom_text(data = plot_dat |> filter(eining == max(eining)),
    #           aes(label = launthegahopur),
    #           hjust = 0, nudge_x = 0.01) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(0, 1.08),
                       labels = label_percent(),
                       breaks = seq(0.1, 0.9, by = 0.1),
                       expand = expansion()) +
    scale_y_continuous(labels = function(x) percent(x - 1)) +
    guides(lty = guide_legend(label.position = "top", keywidth = unit(0.1, "npc"))) +
    facet_wrap("starfsstett", scales = "free_y") +
    theme_tufte() +
    theme(legend.position = "top",
          legend.box.margin = margin(),
          legend.margin = margin(l = 2, r = 2),
          axis.title.y = element_text(hjust = 0),
          axis.title.x = element_text(hjust = 0)) +
    labs(x = "Tekjutíund",
         y = "Launahækkun (%)",
         lty = NULL,
         title = "Dreifing launahækkana (í prósentum) frá 2019 - 2021",
         subtitle = NULL,
         caption = "Kóði: https://github.com/bgautijonsson/tekjur")

p

p

ggsave(plot = p, filename = "hlutf_breyting_2019-2021.png",
       width = 8, height = 0.7 * 8, scale = 1.3, bg = "white")
```


## Laun 2021

```{r, fig.width = 10, fig.asp = 0.6, out.width = "100%"}
plot_dat <- d |> 
    filter(kyn == "Alls",
           ar %in% c(2021),
           !starfsstett %in% c("Alls", "Iðnaðarmenn", "Verkafólk")) |> 
    mutate(launthegahopur = fct_recode(launthegahopur,
                                       "Almennur markaður" = "Starfsmenn á almennum vinnumarkaði",
                                       "Hið opinbera" = "Opinberir starfsmenn - alls") |> 
               as.character() |> 
               as_factor(),
           laun = laun * 1000,
           ar = ifelse(ar == max(ar), "eftir", "fyrir")) |> 
    mutate(nr = starfsstett |> str_replace_all("[a-zA-Z áíéóðþö \\-]", "") |> parse_number(),
           starfsstett = str_replace(starfsstett, "\\([0-9]\\)", ""),
           starfsstett = fct_reorder(starfsstett, nr))

p <- plot_dat |> 
    ggplot(aes(eining, laun)) +
    geom_line(aes(lty = launthegahopur)) +
    geom_rangeframe() +
    scale_x_continuous(limits = c(0, 1.08),
                       labels = label_percent(),
                       breaks = seq(0.1, 0.9, by = 0.1),
                       expand = expansion()) +
    scale_y_continuous(labels = label_number()) +
    guides(lty = guide_legend(label.position = "top", keywidth = unit(0.1, "npc"))) +
    facet_wrap("starfsstett", scales = "free_y") +
    theme_tufte() +
    theme(legend.position = "top",
          legend.box.margin = margin(),
          legend.margin = margin(l = 2, r = 2),
          axis.title.y = element_text(hjust = 0),
          axis.title.x = element_text(hjust = 0)) +
    labs(x = "Tekjutíund",
         y = "Launahækkun (Krónur)",
         lty = NULL,
         title = "Dreifing almennra heildarlauna 2021 eftir vinnumarkaði",
         subtitle = NULL,
         caption = "Kóði: https://github.com/bgautijonsson/tekjur")

p

ggsave(plot = p, filename = "heildarlaun.png",
       width = 8, height = 0.7 * 8, scale = 1.3, bg = "white")
```